const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

const GET_MORE_USERS_REQUEST = 'GET_MORE_USERS_REQUEST';
const GET_MORE_USERS_SUCCESS = 'GET_MORE_USERS_SUCCESS';

export {
  GET_USERS_REQUEST,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,
  GET_MORE_USERS_REQUEST,
  GET_MORE_USERS_SUCCESS,
};
